In [69]:
import Layer as ffp
import Backpropagation as bp
import Lossfunction as lf

import importlib
importlib.reload(ffp)
importlib.reload(bp)
importlib.reload(lf)

from Layer import *
from Backpropagation import *
from Lossfunction import *
import numpy as np

# Contoh penggunaan Layer dan Dense
pada kode di bawah ini adalah cara pemanggilan untuk Layer dan melakukan forward propagation

inputs: np.array 2Dimensi 

untuk memanggil Layer baru kita bisa memanggil Dense 
Dense: 
    neurons: jumlah neuron yang ada pada layer tersebut
    activation: activation function yang akan digunakan untuk output dari layer tersebut 
    inputShape: inputya dalam dimensi berapa dalam contoh dibawah digunakan (3,) yang berarti matriks 3 x 1 (row x col)

Untuk melakukan feed forward propagation kita bisa memanggil fungsi method call
```python
outputs = dense_layer.call(inputs)
```

In [75]:
# Use a tuple (3,) for inputShape instead of (3)
inputs = np.array([[0.5, 0.2, -0.1]])

# Create a Dense layer with 4 neurons, 'relu' activation, and input shape (3,)
dense_layer = Dense(neurons=4, activation='relu', inputShape=(3,))
outputs = dense_layer.call(inputs)
print("Layer hidden 1 output:", outputs)

# Create a Dense layer with 2 neurons, 'sigmoid' activation, and input shape (4,)
dense_layer2 = Dense(neurons=2, activation='sigmoid', inputShape=(4,))
outputs2 = dense_layer2.call(outputs)
print("Layer output:", outputs2)


Layer hidden 1 output: [[0.90722451 0.         0.34508036 0.        ]]
Layer output: [[0.69697372 0.53457107]]


## contoh penggunaan untuk inisialisi bobot sesuai spesifikasi 

contoh 1: bobot default 

contoh 2: untuk pemanggilan menggunakan uniform method 

contoh 3: untuk pemanggilan menggunkan uniform normal 

contoh 4: untuk zero inisialisasi 

In [71]:

# --- Contoh Penggunaan ---

# Contoh 1: Inisialisasi dengan metode default (misalnya Xavier uniform)
inputs = np.array([[0.5, 0.2, -0.1]])
dense_layer = Dense(neurons=4, activation='relu', inputShape=(3,))
outputs = dense_layer.call(inputs)
print("Layer hidden 1 output (default/Xavier):", outputs)

# Contoh 2: Inisialisasi dengan metode uniform dengan parameter khusus
weightInitParams = {'lower_bound': -0.1, 'upper_bound': 0.1, 'seed': 42}
dense_layer_uniform = Dense(neurons=4, activation='relu', inputShape=(3,),
                            weightInit='uniform', weightInitParams=weightInitParams)
outputs_uniform = dense_layer_uniform.call(inputs)
print("Layer hidden 1 output (uniform):", outputs_uniform)

# Contoh 3: Inisialisasi dengan metode normal dengan parameter khusus
weightInit_params_normal = {'mean': 0, 'variance': 0.01, 'seed': 42}
dense_layer_normal = Dense(neurons=4, activation='relu', inputShape=(3,),
                           weightInit='normal', weightInitParams=weightInit_params_normal)
outputs_normal = dense_layer_normal.call(inputs)
print("Layer hidden 1 output (normal):", outputs_normal)

# Contoh 4: Inisialisasi dengan zero initialization
dense_layer_zero = Dense(neurons=4, activation='relu', inputShape=(3,),
                         weightInit='zero')
outputs_zero = dense_layer_zero.call(inputs)
print("Layer hidden 1 output (zero):", outputs_zero)

Layer hidden 1 output (default/Xavier): [[0.         0.87037067 0.         0.2725815 ]]
Layer hidden 1 output (uniform): [[0.05787863 0.         0.         0.        ]]
Layer hidden 1 output (normal): [[0.02615464 0.00445073 0.15171032 0.186983  ]]
Layer hidden 1 output (zero): [[0. 0. 0. 0.]]


## Contoh print untuk tiap layer

Gunakan kode dibawah untuk merepresentasikan bias dan bobot pada layar
```python
print(dense_layer.__repr__())
```


atau untuk print satu-satu bisa digunakan untuk print per attributenya
```python
print(dense_layer.activation.__name__) # print dense_layer activation
print(dense_layer.bias) # print bias
print(dense_layer.weight) # print bobot
```


In [72]:
inputs = np.array([[0.5, 0.2, -0.1]])

dense_layer = Dense(neurons=4, activation='relu', inputShape=(3,))
outputs = dense_layer.call(inputs)
print("Layer hidden 1:", outputs)
print(dense_layer.__repr__())

dense_layer2 = Dense(neurons=2, activation='sigmoid', inputShape=(4,))
outputs2 = dense_layer2.call(outputs)
print("Layer output:", outputs2)
print(dense_layer2.__repr__())

# --- Contoh Penggunaan per Attribute---

print(f"name: {dense_layer.activation.__name__}") # Get activation
print(f"bias: {dense_layer.bias}") # Get biases
print(f"weight: {dense_layer.weights}") # Get weights


Layer hidden 1: [[0.         0.26900941 0.21736785 0.        ]]
Layer: 
activation = relu
weights 
 = [[ 0.56626722  0.36688287 -0.29579857 -0.63792801]
 [ 0.8465941  -0.30256811 -0.75408817 -0.74673617]
 [ 0.64343454  0.19206329  0.56869106  0.42538061]]
bias = [-0.51764338  0.16528793  0.57295387 -0.91378674]

Layer output: [[0.60035128 0.73954887]]
Layer: 
activation = sigmoid
weights 
 = [[-0.24293125  0.10408126]
 [ 0.65880933  0.2370395 ]
 [ 0.7234138   0.15470429]
 [ 0.40914367 -0.90835123]]
bias = [0.07245618 0.94623153]

name: relu
bias: [-0.51764338  0.16528793  0.57295387 -0.91378674]
weight: [[ 0.56626722  0.36688287 -0.29579857 -0.63792801]
 [ 0.8465941  -0.30256811 -0.75408817 -0.74673617]
 [ 0.64343454  0.19206329  0.56869106  0.42538061]]


In [73]:
#contoh forward yang ada di kelas

inputs = np.array([
    [0, 0],
    [0, 1], 
    [1, 0],
    [1, 1]
])

weight_input = np.array([
    [0, -1],
    [1, 1],
    [1, 1]
])


hidden_layer = Dense(neurons=2, activation='relu', inputShape=(2,), inputWeight=weight_input)
outputs = hidden_layer.call(inputs)

print("Layer hidden 1 output:\n", outputs)

weight_hidden = np.array([
    [0],
    [1], 
    [-2]
])

output_layer = Dense(neurons=1, activation='relu', inputShape=(2,), inputWeight=weight_hidden)
outputs = output_layer.call(outputs)

print("Layer output:\n", outputs)

Layer hidden 1 output:
 [[0. 0.]
 [1. 0.]
 [1. 0.]
 [2. 1.]]
Layer output:
 [[0.]
 [1.]
 [1.]
 [0.]]


## How to use Backpropagation 

1. Inisiasi tiap layer dulu 
2. Panggil Constructor dari Backpropagation 
    - learning_rate: float
    - batch_size: int
    - epochs: int
    - loss: string
        - 'mse'
        - 'binary_crossentropy'
        - 'categorical_crossentropy'
    - verbose: boolean

3. compile atau masukkan layer ke dalam instance dari Backpropagation 
4. masukkan data untuk di train

In [74]:

# inisiasi tiap layer

weight_init_params = {'lower_bound': -0.1, 'upper_bound': 0.1, 'seed': 41} 
hidden_layer = Dense(neurons=4, activation="relu", inputShape=(3,), weightInit="uniform", weightInitParams=weight_init_params)
hidden_layer2 = Dense(neurons=3, activation="relu", inputShape=(4,), weightInit="uniform", weightInitParams=weight_init_params)
output_layer = Dense(neurons=2, activation="sigmoid", inputShape=(3,), weightInit="uniform", weightInitParams=weight_init_params)

# Create and compile the backpropagation optimizer
bp = Backpropagation(
        learning_rate=0.01,
        batch_size=1000, 
        epochs=10, 
        loss='mse',
        verbose=True ### verbose dinyalakan
    )

bp.compile([hidden_layer, hidden_layer2 ,output_layer])

x_train = np.array([
    [0.5, -0.2, 0.1],
    [0.1, 0.4, -0.3],
    [-0.3, 0.2, 0.6],
    [0.7, -0.8, 0.9],
    [0.2, 0.5, -0.4]
])
y_train = np.array([
    [1, 0],
    [0, 1],
    [1, 0],
    [0, 1],
    [1, 0]
])

### prediksi sebelum training 
print("Prediction before training:")
print(bp.predict(x_train))
print()


bp.train(x_train, y_train)


### prediksi setelah training
print("\nPrediction after training:")
print(bp.predict(x_train))



Prediction before training:
[[0.49405132 0.48653921]
 [0.49405132 0.48653921]
 [0.49405132 0.48653921]
 [0.49405132 0.48653921]
 [0.49405132 0.48653921]]

Epoch 1/10 - loss: 0.2494
Epoch 2/10 - loss: 0.2493
Epoch 3/10 - loss: 0.2493
Epoch 4/10 - loss: 0.2493
Epoch 5/10 - loss: 0.2493
Epoch 6/10 - loss: 0.2493
Epoch 7/10 - loss: 0.2493
Epoch 8/10 - loss: 0.2493
Epoch 9/10 - loss: 0.2493
Epoch 10/10 - loss: 0.2493

Prediction after training:
[[0.49471147 0.48600067]
 [0.49471147 0.48600067]
 [0.49471147 0.48600067]
 [0.49471147 0.48600067]
 [0.49471147 0.48600067]]
