In [1]:
import Layer as ffp
import importlib
importlib.reload(ffp)

from Layer import *
import numpy as np

# Contoh penggunaan kode
pada kode di bawah ini adalah cara pemanggilan untuk Layer dan melakukan forward propagation

inputs: np.array 2Dimensi 

untuk memanggil Layer baru kita bisa memanggil Dense 
Dense: 
    neurons: jumlah neuron yang ada pada layer tersebut
    activation: activation function yang akan digunakan untuk output dari layer tersebut 
    inputShape: inputya dalam dimensi berapa dalam contoh dibawah digunakan (3,) yang berarti matriks 3 x 1 (row x col)

Untuk melakukan feed forward propagation kita bisa memanggil fungsi method call
```python
outputs = dense_layer.call(inputs)
```

In [ ]:
# Use a tuple (3,) for inputShape instead of (3)
inputs = np.array([[0.5, 0.2, -0.1]])

# Create a Dense layer with 4 neurons, 'relu' activation, and input shape (3,)
dense_layer = Dense(neurons=4, activation='relu', inputShape=(3,))
outputs = dense_layer.call(inputs)
print("Layer hidden 1 output:", outputs)

# Create a Dense layer with 2 neurons, 'sigmoid' activation, and input shape (4,)
dense_layer2 = Dense(neurons=2, activation='sigmoid', inputShape=(4,))
outputs2 = dense_layer2.call(outputs)
print("Layer output:", outputs2)


Layer hidden 1 output: [[0.09222589 1.04375267 0.         1.09028192]]
Layer output: [[0.39535104 0.39945488]]


## contoh penggunaan untuk inisialisi bobot sesuai spesifikasi 

contoh 1: bobot default 

contoh 2: untuk pemanggilan menggunakan uniform method 

contoh 3: untuk pemanggilan menggunkan uniform normal 

contoh 4: untuk zero inisialisasi 

In [ ]:

# --- Contoh Penggunaan ---

# Contoh 1: Inisialisasi dengan metode default (misalnya Xavier uniform)
inputs = np.array([[0.5, 0.2, -0.1]])
dense_layer = Dense(neurons=4, activation='relu', inputShape=(3,))
outputs = dense_layer.call(inputs)
print("Layer hidden 1 output (default/Xavier):", outputs)

# Contoh 2: Inisialisasi dengan metode uniform dengan parameter khusus
weightInitParams = {'lower_bound': -0.1, 'upper_bound': 0.1, 'seed': 42}
dense_layer_uniform = Dense(neurons=4, activation='relu', inputShape=(3,),
                            weightInit='uniform', weightInitParams=weightInitParams)
outputs_uniform = dense_layer_uniform.call(inputs)
print("Layer hidden 1 output (uniform):", outputs_uniform)

# Contoh 3: Inisialisasi dengan metode normal dengan parameter khusus
weightInit_params_normal = {'mean': 0, 'variance': 0.01, 'seed': 42}
dense_layer_normal = Dense(neurons=4, activation='relu', inputShape=(3,),
                           weightInit='normal', weightInitParams=weightInit_params_normal)
outputs_normal = dense_layer_normal.call(inputs)
print("Layer hidden 1 output (normal):", outputs_normal)

# Contoh 4: Inisialisasi dengan zero initialization
dense_layer_zero = Dense(neurons=4, activation='relu', inputShape=(3,),
                         weightInit='zero')
outputs_zero = dense_layer_zero.call(inputs)
print("Layer hidden 1 output (zero):", outputs_zero)

Layer hidden 1 output (default/Xavier): [[0.         0.         0.37496817 1.78596728]]
Layer hidden 1 output (uniform): [[0.08576399 0.         0.         0.        ]]
Layer hidden 1 output (normal): [[0.07582605 0.         0.21647917 0.33928599]]
Layer hidden 1 output (zero): [[0. 0. 0. 0.]]


## Contoh print untuk tiap layer

Gunakan kode dibawah untuk merepresentasikan bias dan bobot pada layar
```python
print(dense_layer.__repr__())
```


atau untuk print satu-satu bisa digunakan untuk print per attributenya
```python
print(dense_layer.activation.__name__) # print dense_layer activation
print(dense_layer.bias) # print bias
print(dense_layer.weight) # print bobot
```


In [12]:
inputs = np.array([[0.5, 0.2, -0.1]])

dense_layer = Dense(neurons=4, activation='relu', inputShape=(3,))
outputs = dense_layer.call(inputs)
print("Layer hidden 1 output:", outputs)
print(dense_layer.__repr__())

dense_layer2 = Dense(neurons=2, activation='sigmoid', inputShape=(4,))
outputs2 = dense_layer2.call(outputs)
print("Layer output:", outputs2)
print(dense_layer2.__repr__())

# --- Contoh Penggunaan per Attribute---

print(f"name: {dense_layer.activation.__name__}") # Get activation
print(f"bias: {dense_layer.bias}") # Get biases
print(f"weight: {dense_layer.weights}") # Get weights


Layer hidden 1 output: [[1.13381352 0.         0.         0.        ]]
Layer: 
activation = relu
weights 
 = [[ 0.79878452  0.00210634  0.5903757  -0.89266563]
 [-0.33676281 -0.74219259  0.74577008  0.39102448]
 [-0.12676945  0.46412611  0.70561458 -0.35386656]]
bias = [ 0.39454844 -0.09550584 -0.78628399 -0.31700335]

Layer output: [[0.19354983 0.06454578]]
Layer: 
activation = sigmoid
weights 
 = [[-0.14118527 -0.71615106]
 [-0.92813844 -0.234482  ]
 [-0.85974723  0.41389049]
 [ 0.33048532  0.95613027]]
bias = [-0.63351466 -0.93083783]

name: relu
bias: [ 0.39454844 -0.09550584 -0.78628399 -0.31700335]
weight: [[ 0.79878452  0.00210634  0.5903757  -0.89266563]
 [-0.33676281 -0.74219259  0.74577008  0.39102448]
 [-0.12676945  0.46412611  0.70561458 -0.35386656]]
